### ISSUE TITLE
File Names

### ISSUE THREAD

**Issue by ritvikgautam** [BitcoinDictionary/bitcoindictionary#11]
Wouldn't it be better if we could define how a file should be named. 
Various ways I've found the filenames are
ThisIsExample
This-Is-Example
thisisexample
this
tie

If we could come up with a definite way of naming files, that'd be better and increase the usability.

**Comment by tkembo** [comment]
The format I have been using was This_Is_Example - an underscore to separate words. The reason I had picked that particular format was because if someone made a quick glance at the word, it would be clear that it was two words instead of one. What do you think?

**Comment by ritvikgautam** [comment]
You're right! 
My point was just that there should be a uniform format for all the words. So let's say if I want to run a script on this, it would be easy that way. 

So, if we want to convert the file names in one particular format, is there any way you know other than doing it manually?

**Comment by tkembo** [comment]
The only way I can think of is to do it manually

**Comment by ritvikgautam** [comment]
Okay! I'll take on the task.
And I'll also update the Readme file.

**Comment by tkembo** [comment]
Thanks. You're the greatest!

**Comment by ritvikgautam** [comment]
You're too kind. :)
